//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reservas_y_Citas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public Nullable<int> ciudad { get; set; }
        public string telefono { get; set; }
    }
}
