//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reservas_y_Citas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public Nullable<int> paciente { get; set; }
        public Nullable<int> medico { get; set; }
        public Nullable<int> funcionario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_reservada { get; set; }
        public Nullable<int> estados { get; set; }
        public Nullable<double> monto { get; set; }
    }
}
